$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: green-10
endpoint_name: endpoint-workshop-aml
model: azureml:mlopsmodeltraining:1
code_configuration:
  code: scoring
  scoring_script: score.py
environment:
  image: mcr.microsoft.com/azureml/curated/sklearn-0.24-ubuntu18.04-py37-cpu:latest
instance_type: Standard_E2s_v3
instance_count: 1
