trigger:
- main

variables:
- group: 'mlops-workshop'
- group: 'mlops-workshop-keyvault'

stages:
- stage: BuildModelTraining
  jobs:
  - job: BuildModelTraining

    pool:
      vmImage: ubuntu-latest

    steps:

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true
        architecture: 'x64'

    - script: |
        pip install databricks-api
        echo dependancies installed - submitting the job
        echo key-vault-secret: $(key-vault-secret)
        python pipeline/databricks-model-training-automation.py --token $(adb_token) --build-id $(Build.BuildNumber) --workspace-name $(workspace_name) --subscription-id $(subscription_id) --resource-group $(resource_group) --service-principal-id $(sp_id) --tenant-id $(sp_tenant_id) --adb-secrets-scope $(adb_secrets_scope_2) --adb-sp-secret-key $(adb_sp_secret_key_2) --repo-id $(adb_repo_id) --databricks-host $(adb_host) --cluster-id $(cluster_id)
      displayName: 'Model training'
- stage: ReleaseModelDeployment
  dependsOn: BuildModelTraining
  jobs:
  - job: ReleaseModelDeployment

    pool:
      vmImage: ubuntu-latest

    steps:
    - script: |
        az login --service-principal  --username $(sp_id) --password $(sp-secret-value) --tenant $(sp_tenant_id)
        az account show
        az extension add -n ml
        az account set -s $(subscription_id)
        az configure --defaults workspace=$(workspace_name) group=$(resource_group) location=$(location)
        az ml online-endpoint create  -f aml/deployment/endpoint.yml
        az ml online-deployment create  -f aml/deployment/deployment.yml
