trigger:
 - main

variables:
- group: 'mlops-workshop'
- group: 'mlops-workshop-keyvault'

pool:
    vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'final-day-sp-connecion'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az group list -o table

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
    addToPath: true
    architecture: 'x64'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'final-day-sp-connecion'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az account show
      pip install azureml-sdk
      python aml/training/pipeline/end_to_end_train_pipeline.py --workspace-name $(workspace_name) --subscription-id $(subscription_id) --resource-group $(resource_group) --adb-attached-compute-name $(adb_attached_compute_name) --cluster-id $(cluster_id) --aml-train-cluster-id $(hd-cluster) --aml-register-cluster-id  $(small-cluster)

# stages:
# - stage: BuildModelTraining
#   jobs:
#   - job: BuildModelTraining

#     pool:
#       vmImage: ubuntu-latest

#     steps:

#     - task: UsePythonVersion@0
#       inputs:
#         versionSpec: '3.8'
#         addToPath: true
#         architecture: 'x64'

#     - script: |
#         az login --service-principal  --username $(sp_id) --password $(sp_secret) --tenant $(sp_tenant_id)
#         az account show

#         pip install azureml-core
#         pip install azureml-pipeline-core
#         pip install azureml-pipeline-steps

#         python aml/training/pipeline/main.py
#       displayName: 'Model training'


# - stage: ReleaseModelDeployment
#   dependsOn: BuildModelTraining
#   jobs:
#   - job: ReleaseModelDeployment

#     pool:
#       vmImage: ubuntu-latest

#     steps:
#     - script: |
#         az login
#         az extension add -n ml
#         az account set -s "Workload1"
#         az configure --defaults workspace=amlhudua group=mlops
#         az ml online-endpoint update  -f aml/deployment/endpoint.yml
#         az ml online-deployment update  -f aml/deployment/deployment.yml
