trigger: none

variables:
- group: mlops-workshop

stages:
- stage: BuildModelTraining
  jobs:
  - job: BuildModelTraining

    pool:
      vmImage: ubuntu-latest

    steps:

    - task: UsePythonVersion@0
      displayName: 'Model training'        
      inputs:
        versionSpec: '3.x'
        addToPath: true
        architecture: 'x64'
        azureSubscription: '$(azure_svc_name)'
        scriptLocation: 'inlineScript'
        inlineScript: 'az account show'


    # - script: |
    #       az --version
    #       az account show
    #       echo '$(azure_svc_name)'
    #       pip install azureml-core
    #       pip install azureml-pipeline-core
    #       pip install azureml-pipeline-steps
    #       python aml/training/pipeline/main.py

# - stage: ReleaseModelDeployment
#   dependsOn: BuildModelTraining
#   jobs:
#   - job: ReleaseModelDeployment

#     pool:
#       vmImage: ubuntu-latest

#     steps:
#     - script: |
#         az login
#         az extension add -n ml
#         az account set -s "Workload1"
#         az configure --defaults workspace=amlhudua group=mlops
#         az ml online-endpoint update  -f aml/deployment/endpoint.yml
#         az ml online-deployment update  -f aml/deployment/deployment.yml
