trigger:
- main

variables:
- group: 'mlops-workshop'

stages:

- stage: ReleaseModelDeployment
  dependsOn: BuildModelTraining
  jobs:
  - job: ReleaseModelDeployment

    pool:
      vmImage: ubuntu-latest

    steps:
    - script: |
        az login --service-principal  --username $(sp_id) --password $(sp_secret) --tenant $(sp_tenant_id)
        az account show
        az extension add -n ml
        az account set -s $(subscription_id)
        az configure --defaults workspace=$(workspace_name) group=$(resource_group) location=$(location)
        az ml online-endpoint create  -f aml/endpoint.yml
        az ml online-deployment create  -f aml/deployment.yml
