trigger:
- main

variables:
- group: 'mlops-workshop'
- group: 'mlops-workshop-keyvault'

pool:
    vmImage: ubuntu-latest

stages:
- stage: BuildModelTraining
  jobs:
  - job: BuildModelTraining

    pool:
      vmImage: ubuntu-latest

    steps:

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'final-day-sp-connecion'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az group list -o table

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'
        addToPath: true
        architecture: 'x64'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'final-day-sp-connecion'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az account show
          pip install azureml-core
          pip install azureml-pipeline-core
          pip install azureml-pipeline-steps
          python aml/training/pipeline/main.py --workspace-name $(workspace_name) --subscription-id $(subscription_id) --resource-group $(resource_group)
        displayName: 'Model training'

- stage: ReleaseModelDeployment
  dependsOn: BuildModelTraining
  jobs:
  - job: ReleaseModelDeployment

    pool:
      vmImage: ubuntu-latest

    steps:

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'final-day-sp-connecion'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az account show
          az extension add -n ml
          az account set -s $(subscription_id)
          az configure --defaults workspace=$(workspace_name) group=$(resource_group) location=$(location)
          az ml online-endpoint create  -f aml/deployment/endpoint.yml
          az ml online-deployment create  -f aml/deployment/deployment.yml
        displayName: 'Model Deployment to ME'
