trigger:
- main

variables:
- group: 'mlops-workshop'

stages:
- stage: BuildModelTraining
  jobs:
  - job: BuildModelTraining

    pool:
      vmImage: ubuntu-latest

    steps:

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true
        architecture: 'x64'

    - script: |
        pip install databricks-api
        python pipeline/databricks-model-training-automation.py $(adb_token) $(Build.BuildNumber)
      displayName: 'Model training'
- stage: ReleaseModelDeployment
  dependsOn: BuildModelTraining
  jobs:
  - job: ReleaseModelDeployment

    pool:
      vmImage: ubuntu-latest

    steps:
    - script: |
        az login --service-principal  --username $(sp_id) --password $(sp_secret) --tenant $(sp_tenant_id)
        az account show
        az extension add -n ml
        az account set -s $(subscription_id)
        az configure --defaults workspace=$(workspace_name) group=$(resource_group) location=$(location)
        az ml online-endpoint create  -f aml/deployment/endpoint.yml
        az ml online-deployment create  -f aml/deployment/deployment.yml
